services:
    gateway:
        build:
            context: ./gateway/docker
            dockerfile: ./development/nginx/nginx.dockerfile
        container_name: ${PROJECT_NAME}-gateway
        volumes:
            - ./nginx-log/gateway:/var/log/nginx
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - frontend
            - api

    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: ./development/php-fpm/php.dockerfile
        container_name: ${PROJECT_NAME}-api-php-fpm
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
        volumes:
            - ./api:/app
            - ./nginx-log/api-php-fpm:/var/log/nginx

    api-php-cli:
        build:
            args:
                user: ${USER}
                uid: 1000
                group: ${USER}
            context: ./api/docker
            dockerfile: ./development/php-cli/Dockerfile
        container_name: ${PROJECT_NAME}-api-php-cli
        volumes:
            - ./api:/app

    api:
        build:
            context: ./api/docker
            dockerfile: ./development/nginx/nginx.dockerfile
        depends_on:
            - api-php-fpm
        container_name: ${PROJECT_NAME}-api
        volumes:
            - ./api:/app
            - ./nginx-log/api:/var/log/nginx

    frontend:
        build:
            context: ./frontend/docker
            dockerfile: ./development/nginx/nginx.dockerfile
        container_name: ${PROJECT_NAME}-frontend
        volumes:
            - ./frontend:/app
            - ./frontend/docker/common/nginx/conf.d:/etc/nginx/conf.d
            - ./nginx-log/frontend:/var/log/nginx
